- name: Initialize and Apply Terraform to create VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Print current working directory
      command: pwd
      register: pwd_output

    - name: Show current working directory
      debug:
        msg: "Current working directory is: {{ pwd_output.stdout }}"

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: ./../terraform/

    - name: Apply Terraform to provision VM
      command: terraform apply -auto-approve
      args:
        chdir: ./../terraform/
      register: terraform_output

    - name: Show Terraform Apply Output
      debug:
        msg: "{{ terraform_output.stdout }}"

    - name: Get VM Public IP from Terraform Output
      command: terraform output public_ip_address
      args:
        chdir: ./../terraform/
      register: vm_public_ip_output

    - name: Show VM Public IP
      debug:
        msg: "The Public IP of the created VM is: {{ vm_public_ip_output.stdout }}"

    - name: Check Azure Virtual Machine Status
      command: az vm show --resource-group example-resources --name example-vm --query "provisioningState"
      register: vm_status_output

    - name: Show Azure VM Status
      debug:
        msg: "The VM provisioning status is: {{ vm_status_output.stdout }}"
